CREATE TABLE USUARIOS (
	ID VARCHAR(20) PRIMARY KEY,
    FOTO VARCHAR(200);
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    DOMICILIO INT(100),
    TELEFONO INT(20),
    EMAIL VARCHAR(100)
);
