//BD INTERNA

CREATE TABLE USUARIOS (
    ID INTEGER PRIMARY KEY autoincrement,
    FOTO VARCHAR(400),
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    DOMICILIO VARCHAR(100),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100)
);

CREATE TABLE GALERIA (
    ID INTEGER PRIMARY KEY,
    URL VARCHAR(200)
);

CREATE TABLE DOMICILIO(
    ID INTEGER PRIMARY KEY,
    DIRECCION VARCHAR(200)
);

CREATE TABLE TELEFONO(
    ID INTEGER PRIMARY KEY,
    NUMERO VARCHAR(15)
);
