BD INTERNA y EXTERNA

CREATE TABLE USUARIOS (
	ID VARCHAR(20) PRIMARY KEY,
    FOTO VARCHAR(200),
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    DOMICILIO VARCHAR(200),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100)
);


